### ISSUE TITLE
Enable multitouch testing on CT

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/aqua#106]
We would like to enable multitouch fuzzing on CT testing. It would be good to cover multitouch testing on CT in general, but this will also cover magnification testing in CT.  First step is to fuzz everything with `?fuzzPointers=3`.

First step is to test all sims with multitouch fuzzing and get a sense of how many problems there are. If there is a manageable amount of issues, they will be resolved, the number of pointers will be increased. If too many issues are present we should reassess.

We also need to make sure that multitouch testing doesn't bias toward `always` testing with multitouch. Some of the fuzzing needs to remain as single presses. We need to inspect the implementation of fuzzing to understand this.

**Comment by jessegreenberg** [comment]
> We also need to make sure that multitouch testing doesn't bias toward always testing with multitouch. Some of the fuzzing needs to remain as single presses. We need to inspect the implementation of fuzzing to understand this.

Looking at InputFuzzer.fuzzEvents:

Every frame there is a chance that 0 - N actions will be made, where N default is currently 100. Actions are random in their selection, while making sure that the number of pointers down doesn't exceed `?fuzzPointers` value and `up` events can only go down if there are active pointers.

I sampled 10,000 actions with `?fuzz&fuzzPointers=3` and the average number of pointers was 1.7. So most of the time there are multiple presses down. After fuzzing for about 30 seconds with `?fuzzPointers=2` the average number of pointers stabilized at 1.18. Still a slight bias to  more than one, but better. Lets go with ?fuzzPointers=2 when we enable this.

**Comment by jessegreenberg** [comment]
When I run fuzzing with `?fuzzPointers=2`, I only encounter these four errors:

```
balloons-and-static-electricity
Uncaught Error: Assertion failed: cannot set to grabbable if already set that way
Error: Assertion failed: cannot set to grabbable if already set that way
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at GrabDragInteraction.releaseDraggable (http://10.0.0.179:8080/scenery-phet/js/accessibility/GrabDragInteraction.js:443:15)
    at PressListener.release [as _releaseListener] (http://10.0.0.179:8080/scenery-phet/js/accessibility/GrabDragInteraction.js:393:16)
    at PressListener.onRelease (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:619:10)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at PressListener.release (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:418:25)
    at PressListener.interrupt (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:475:12)
    at PressListener.pointerCancel (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:754:12)
    at Input.dispatchToListeners (http://10.0.0.179:8080/scenery/js/input/Input.js:1852:25)
    at Input.dispatchEvent (http://10.0.0.179:8080/scenery/js/input/Input.js:1806:10)
friction
Uncaught Error: Assertion failed: cannot set to grabbable if already set that way
Error: Assertion failed: cannot set to grabbable if already set that way
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at FrictionGrabDragInteraction.releaseDraggable (http://10.0.0.179:8080/scenery-phet/js/accessibility/GrabDragInteraction.js:443:15)
    at PressListener.release [as _releaseListener] (http://10.0.0.179:8080/scenery-phet/js/accessibility/GrabDragInteraction.js:393:16)
    at PressListener.onRelease (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:619:10)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at PressListener.release (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:418:25)
    at PressListener.interrupt (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:475:12)
    at PressListener.pointerCancel (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:754:12)
    at Input.dispatchToListeners (http://10.0.0.179:8080/scenery/js/input/Input.js:1852:25)
    at Input.dispatchEvent (http://10.0.0.179:8080/scenery/js/input/Input.js:1806:10)
make-a-ten
Uncaught Error: Assertion failed: Did not find matching Node
Error: Assertion failed: Did not find matching Node
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at MakeATenGameScreenView.findPaperNumberNode (http://10.0.0.179:8080/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js:147:15)
    at MakeATenGameScreenView.tryToCombineNumbers (http://10.0.0.179:8080/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js:158:30)
    at DragListener.end [as _end] (http://10.0.0.179:8080/make-a-ten/js/make-a-ten/common/view/PaperNumberNode.js:89:7)
    at http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:344:25
    at DragListener.onRelease (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:621:17)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:418:25)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:340:37)
    at DragListener.pointerUp (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:730:12)
masses-and-springs-basics
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at Tandem.removeChild (http://10.0.0.179:8080/tandem/js/Tandem.js:292:15)
    at Tandem.dispose (http://10.0.0.179:8080/tandem/js/Tandem.js:300:23)
    at Tandem.removePhetioObject (http://10.0.0.179:8080/tandem/js/Tandem.js:211:25)
    at MutableOptionsNodeConstructor.dispose (http://10.0.0.179:8080/tandem/js/PhetioObject.js:556:19)
    at MutableOptionsNodeConstructor.dispose (http://10.0.0.179:8080/scenery/js/nodes/Node.js:5351:36)
    at MutableOptionsNodeConstructor.PhetioObject.dispose (http://10.0.0.179:8080/tandem/js/PhetioObject.js:199:20)
    at MutableOptionsNode.disposeCopy (http://10.0.0.179:8080/sun/js/MutableOptionsNode.js:106:26)
    at MutableOptionsNode.replaceCopy (http://10.0.0.179:8080/sun/js/MutableOptionsNode.js:95:12)
    at listener (http://10.0.0.179:8080/axon/js/Multilink.js:46:20)
```

The friction and BASE issues are likely the same problem, and I expect would likely show up in other sims with a11y.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/scenery-phet/issues/622 resolves the GrabDragInteraction issues. the masses-and-springs-basics issue is handled in https://github.com/phetsims/masses-and-springs-basics/issues/67. The only issue remaining is in make-a-ten.

**Comment by jessegreenberg** [comment]
A new one popped up
```
fractions-intro
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at CircularSceneNode.getBucketPosition (http://10.0.0.179:8080/fractions-common/js/intro/view/ContainerSetScreenView.js:98:17)
    at http://10.0.0.179:8080/fractions-common/js/intro/view/CellSceneNode.js:222:54
    at DragListener.end [as _end] (http://10.0.0.179:8080/fractions-common/js/intro/view/PieceNode.js:81:18)
    at http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:344:25
    at DragListener.onRelease (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:621:17)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:418:25)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:340:37)
    at DragListener.interrupt (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:475:12)
```

**Comment by jessegreenberg** [comment]
Running tests again locally with longer duration before committing to change because https://github.com/phetsims/aqua/issues/106#issuecomment-684062198 did not appear first run through. Currently at 'B' sims with `testDuration=60000` and now issues found.

**Comment by jessegreenberg** [comment]
Here is the new list after fuzzing for one minute per sim
<details>

```
buoyancy
Uncaught Error: Assertion failed: Cubic start should be finite: Vector2(-Infinity, 0)
Error: Assertion failed: Cubic start should be finite: Vector2(-Infinity, 0)
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at Cubic.invalidate (http://10.0.0.179:8080/kite/js/segments/Cubic.js:316:15)
    at new Cubic (http://10.0.0.179:8080/kite/js/segments/Cubic.js:57:8)
    at Function.fillCrossSectionVertexArray (http://10.0.0.179:8080/density-buoyancy-common/js/buoyancy/model/BoatDesign.js:289:19)
    at http://10.0.0.179:8080/density-buoyancy-common/js/buoyancy/view/BoatView.js:79:18
    at listener (http://10.0.0.179:8080/axon/js/Multilink.js:46:20)
    at TinyEmitter.emit (http://10.0.0.179:8080/axon/js/TinyEmitter.js:71:18)
    at InterpolatedProperty._notifyListeners (http://10.0.0.179:8080/axon/js/Property.js:277:25)
    at InterpolatedProperty.set (http://10.0.0.179:8080/axon/js/Property.js:175:14)
    at InterpolatedProperty.set value [as value] (http://10.0.0.179:8080/axon/js/Property.js:347:32)
buoyancy
Uncaught Error: Assertion failed: reentry detected, value=-0.14404020023346006, oldValue=-0.1244908943176274
Error: Assertion failed: reentry detected, value=-0.14404020023346006, oldValue=-0.1244908943176274
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at InterpolatedProperty._notifyListeners (http://10.0.0.179:8080/axon/js/Property.js:274:15)
    at InterpolatedProperty.set (http://10.0.0.179:8080/axon/js/Property.js:175:14)
    at InterpolatedProperty.set value [as value] (http://10.0.0.179:8080/axon/js/Property.js:347:32)
    at InterpolatedProperty.setRatio (http://10.0.0.179:8080/density-buoyancy-common/js/common/model/InterpolatedProperty.js:58:16)
    at Boat.step (http://10.0.0.179:8080/density-buoyancy-common/js/buoyancy/model/Boat.js:102:44)
    at http://10.0.0.179:8080/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:304:12
    at Array.forEach ()
    at ObservableArray.forEach (http://10.0.0.179:8080/axon/js/ObservableArray.js:305:25)
    at BuoyancyApplicationsModel.step (http://10.0.0.179:8080/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:303:17)
density
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at Tandem.removeChild (http://10.0.0.179:8080/tandem/js/Tandem.js:292:15)
    at Tandem.dispose (http://10.0.0.179:8080/tandem/js/Tandem.js:300:23)
    at Tandem.removePhetioObject (http://10.0.0.179:8080/tandem/js/Tandem.js:211:25)
    at UtteranceQueue.dispose (http://10.0.0.179:8080/tandem/js/PhetioObject.js:556:19)
    at UtteranceQueue.dispose (http://10.0.0.179:8080/utterance-queue/js/UtteranceQueue.js:345:11)
    at UtteranceQueue.PhetioObject.dispose (http://10.0.0.179:8080/tandem/js/PhetioObject.js:199:20)
    at Display.dispose (http://10.0.0.179:8080/scenery/js/display/Display.js:1845:48)
    at LabelTexture.dispose (http://10.0.0.179:8080/mobius/js/NodeTexture.js:63:19)
    at LabelTexture.dispose (http://10.0.0.179:8080/density-buoyancy-common/js/common/view/LabelTexture.js:40:11)
fractions-intro
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at CircularSceneNode.getBucketPosition (http://10.0.0.179:8080/fractions-common/js/intro/view/ContainerSetScreenView.js:98:17)
    at http://10.0.0.179:8080/fractions-common/js/intro/view/CellSceneNode.js:222:54
    at DragListener.end [as _end] (http://10.0.0.179:8080/fractions-common/js/intro/view/PieceNode.js:81:18)
    at http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:344:25
    at DragListener.onRelease (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:621:17)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:418:25)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:340:37)
    at DragListener.pointerUp (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:730:12)
fractions-mixed-numbers
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at RectangularSceneNode.getBucketPosition (http://10.0.0.179:8080/fractions-common/js/intro/view/ContainerSetScreenView.js:98:17)
    at http://10.0.0.179:8080/fractions-common/js/intro/view/CellSceneNode.js:222:54
    at DragListener.end [as _end] (http://10.0.0.179:8080/fractions-common/js/intro/view/PieceNode.js:81:18)
    at http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:344:25
    at DragListener.onRelease (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:621:17)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:418:25)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:340:37)
    at DragListener.pointerUp (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:730:12)
make-a-ten
Uncaught Error: Assertion failed: Did not find matching Node
Error: Assertion failed: Did not find matching Node
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at MakeATenExploreScreenView.findPaperNumberNode (http://10.0.0.179:8080/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js:147:15)
    at MakeATenExploreScreenView.tryToCombineNumbers (http://10.0.0.179:8080/make-a-ten/js/make-a-ten/common/view/MakeATenCommonView.js:158:30)
    at DragListener.end [as _end] (http://10.0.0.179:8080/make-a-ten/js/make-a-ten/common/view/PaperNumberNode.js:89:7)
    at http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:344:25
    at DragListener.onRelease (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:621:17)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:418:25)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:340:37)
    at DragListener.pointerUp (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:730:12)
masses-and-springs-basics
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at Tandem.removeChild (http://10.0.0.179:8080/tandem/js/Tandem.js:292:15)
    at Tandem.dispose (http://10.0.0.179:8080/tandem/js/Tandem.js:300:23)
    at Tandem.removePhetioObject (http://10.0.0.179:8080/tandem/js/Tandem.js:211:25)
    at MutableOptionsNodeConstructor.dispose (http://10.0.0.179:8080/tandem/js/PhetioObject.js:556:19)
    at MutableOptionsNodeConstructor.dispose (http://10.0.0.179:8080/scenery/js/nodes/Node.js:5351:36)
    at MutableOptionsNodeConstructor.PhetioObject.dispose (http://10.0.0.179:8080/tandem/js/PhetioObject.js:199:20)
    at MutableOptionsNode.disposeCopy (http://10.0.0.179:8080/sun/js/MutableOptionsNode.js:106:26)
    at MutableOptionsNode.replaceCopy (http://10.0.0.179:8080/sun/js/MutableOptionsNode.js:95:12)
    at listener (http://10.0.0.179:8080/axon/js/Multilink.js:46:20)
molecule-polarity
Uncaught TypeError: event.isFromPDOM is not a function
TypeError: event.isFromPDOM is not a function
    at Object.fire (http://10.0.0.179:8080/scenery/js/nodes/RichText.js:1787:22)
    at ButtonListener.setButtonState (http://10.0.0.179:8080/scenery/js/input/ButtonListener.js:115:29)
    at Object.up (http://10.0.0.179:8080/scenery/js/input/ButtonListener.js:79:12)
    at ButtonListener.buttonUp (http://10.0.0.179:8080/scenery/js/input/DownUpListener.js:148:20)
    at ButtonListener.interrupt (http://10.0.0.179:8080/scenery/js/input/DownUpListener.js:173:12)
    at RichTextLink.interruptInput (http://10.0.0.179:8080/scenery/js/nodes/Node.js:2022:38)
    at RichTextLink.interruptSubtreeInput (http://10.0.0.179:8080/scenery/js/nodes/Node.js:2035:10)
    at Node.interruptSubtreeInput (http://10.0.0.179:8080/scenery/js/nodes/Node.js:2039:21)
    at RichText.interruptSubtreeInput (http://10.0.0.179:8080/scenery/js/nodes/Node.js:2039:21)
    at VBox.interruptSubtreeInput (http://10.0.0.179:8080/scenery/js/nodes/Node.js:2039:21)
molecules-and-light
Uncaught Error: Assertion failed: matrix should be a finite Matrix3
Error: Assertion failed: matrix should be a finite Matrix3
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at Node.setMatrix (http://10.0.0.179:8080/scenery/js/nodes/Node.js:2420:15)
    at Node.set matrix [as matrix] (http://10.0.0.179:8080/scenery/js/nodes/Node.js:2425:30)
    at AnimatedPanZoomListener.reposition (http://10.0.0.179:8080/scenery/js/listeners/MultiListener.js:472:29)
    at AnimatedPanZoomListener.reposition (http://10.0.0.179:8080/scenery/js/listeners/PanZoomListener.js:105:11)
    at AnimatedPanZoomListener.addPress (http://10.0.0.179:8080/scenery/js/listeners/MultiListener.js:365:10)
    at AnimatedPanZoomListener.addPress (http://10.0.0.179:8080/scenery/js/listeners/PanZoomListener.js:91:11)
    at AnimatedPanZoomListener.addPress (http://10.0.0.179:8080/scenery/js/listeners/AnimatedPanZoomListener.js:633:11)
    at AnimatedPanZoomListener.convertBackgroundPresses (http://10.0.0.179:8080/scenery/js/listeners/MultiListener.js:458:12)
    at Object.move (http://10.0.0.179:8080/scenery/js/listeners/MultiListener.js:180:18)
projectile-motion
Uncaught Error: Assertion failed: timeToGround: NaN, previousPoint.velocity: Vector2(0, 0), previousPoint.acceleration: Vector2(0, 0), fromIf: true
Error: Assertion failed: timeToGround: NaN, previousPoint.velocity: Vector2(0, 0), previousPoint.acceleration: Vector2(0, 0), fromIf: true
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at Trajectory.step (http://10.0.0.179:8080/projectile-motion/js/common/model/Trajectory.js:245:19)
    at IntroModel.stepModelElements (http://10.0.0.179:8080/projectile-motion/js/common/model/ProjectileMotionModel.js:330:44)
    at EventTimer.step (http://10.0.0.179:8080/phet-core/js/EventTimer.js:123:12)
    at IntroModel.step (http://10.0.0.179:8080/projectile-motion/js/common/model/ProjectileMotionModel.js:318:23)
    at http://10.0.0.179:8080/joist/js/Sim.js:294:20
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at Sim.stepSimulation (http://10.0.0.179:8080/joist/js/Sim.js:970:31)
    at Sim.stepOneFrame (http://10.0.0.179:8080/joist/js/Sim.js:960:12)
    at Sim.runAnimationLoop (http://10.0.0.179:8080/joist/js/Sim.js:940:12)
vector-addition
Uncaught Error: Assertion failed: Cannot drag tip when not on graph
Error: Assertion failed: Cannot drag tip when not on graph
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at VectorNode.updateTipPosition (http://10.0.0.179:8080/vector-addition/js/common/view/VectorNode.js:362:15)
    at tipListener (http://10.0.0.179:8080/vector-addition/js/common/view/VectorNode.js:228:14)
    at TinyEmitter.emit (http://10.0.0.179:8080/axon/js/TinyEmitter.js:71:18)
    at Vector2Property._notifyListeners (http://10.0.0.179:8080/axon/js/Property.js:277:25)
    at Vector2Property.set (http://10.0.0.179:8080/axon/js/Property.js:175:14)
    at Vector2Property.set value [as value] (http://10.0.0.179:8080/axon/js/Property.js:347:32)
    at DragListener.reposition (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:631:36)
    at http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:300:12
    at DragListener.onPress (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:594:17)
vector-addition
Uncaught Error: Assertion failed: reentry detected, value=Vector2(-63.200000000000045, 111.4), oldValue=Vector2(116.00000000000001, -87.00000000000001)
Error: Assertion failed: reentry detected, value=Vector2(-63.200000000000045, 111.4), oldValue=Vector2(116.00000000000001, -87.00000000000001)
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at Vector2Property._notifyListeners (http://10.0.0.179:8080/axon/js/Property.js:274:15)
    at Vector2Property.set (http://10.0.0.179:8080/axon/js/Property.js:175:14)
    at Vector2Property.set value [as value] (http://10.0.0.179:8080/axon/js/Property.js:347:32)
    at DragListener.reposition (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:631:36)
    at DragListener._dragAction.Action.parameters.name (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:244:12)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at DragListener.drag (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:369:22)
    at DragListener.pointerMove (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:782:14)
    at Input.dispatchToListeners (http://10.0.0.179:8080/scenery/js/input/Input.js:1852:25)
```
</details>

**Comment by jessegreenberg** [comment]
Looks like the remaining issues are specific to each sim. Putting on developer meeting to review. In my opinion the remaining list is pretty short so it seems worth working on so we can fuzz with multiple pointers, and also test zoom feature with fuzzing.

**Comment by zepumph** [comment]
@jessegreenberg will make issues in the above repos, and then we will turn this on after those are sorted out.

**Comment by pixelzoom** [comment]
There has been no movement on this issue, and sim-specific issues have not been created.  Labeling for developer meeting to decide how to proceed.   My recommendation is to enabled multi-touch fuzz testing, and have responsible devs fix their sims.

**Comment by ariel-phet** [comment]
@jessegreenberg will be moving this issue forward @pixelzoom

**Comment by jessegreenberg** [comment]
Issues have been made for the list in https://github.com/phetsims/aqua/issues/106#issuecomment-684120323. I am running aqua again locally with ?fuzz&fuzzPointers=2&testDuration=30000, in case anything new has been introduced since last checked. At 'f' sims so far and assertions are the same.

**Comment by jessegreenberg** [comment]
OK, fuzz testing finished and the list of issues is the same. Issues have been created for all. 5 sims in total are still failing. Would devs like this to be enabled now, or would you prefer to wait until these are resolved before changing CT?

**Comment by pixelzoom** [comment]
@jessegreenberg can you please post the query parameters used for the failures that you noted in https://github.com/phetsims/aqua/issues/106#issuecomment-684120323?

**Comment by jessegreenberg** [comment]
The query parameters used were the ones used by aqua:
`ea&audioVolume=0&sound=disabled&testDuration=30000&testConcurrentBuilds=4&brand=phet&fuzz&fuzzPointers=2`

Though I think the important ones are
`ea&fuzz&fuzzPointers=2`

**Comment by pixelzoom** [comment]
> Would devs like this to be enabled now, or would you prefer to wait until these are resolved before changing CT?

My preference is to enable this now, and address the problems now.  Otherwise we'll have to continue to iterate on this again, possibly with new problems on each iteration.

**Comment by zepumph** [comment]
At dev meeting today, we decided to just add it, and handle the errors as they appear on CT.

**Comment by pixelzoom** [comment]
2/4/21 dev meeting:

We noted that there are some new CT issues related to this, and decided to create sim-specific issues to address them.

@jessegreenberg will add an option to phetmarks for this feature, then can close this.

**Comment by jessegreenberg** [comment]
I added a checkbox for fuzzPointers=2 to phetmarks. This can be closed.
