### ISSUE TITLE
[Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#132]
My precommit hooks are saying:

```
Linting passed with results.length: 153
tsc passed
[Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

  at onClose (/Users/samreid/apache-document-root/main/perennial/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
  at ChildProcess.<anonymous> (/Users/samreid/apache-document-root/main/perennial/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
  at ChildProcess.emit (node:events:390:28)
  at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
  at onErrorNT (node:internal/child_process:477:16)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)
]

```

Discovered in https://github.com/phetsims/phet-core/issues/112#issuecomment-1063360880.

Sounds related to https://github.com/puppeteer/puppeteer/issues/5662

**Comment by samreid** [comment]
Somehow not a problem any more:

```
~/apache-document-root/main/axon$ pch
Linting passed with results.length: 55
tsc passed
axon: {
  "ok": true,
  "time": 378,
  "totalTests": 492,
  "passed": 492,
  "failed": 0,
  "errors": []
}
QUnit: no problems detected
```

Closing.
