### ISSUE TITLE
CT malformed invocation failed: string instead of callback

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/aqua#155]
A large number of repos in CT are failing with an error that looks like this:
```
balloons-and-static-electricity : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659438233179/phet-io-wrappers/phet-io-wrappers-tests.html?sim=balloons-and-static-electricity&phetioDebug=true&phetioWrapperDebug=true
8 out of 9 tests passed. 1 failed.
CrossFrameMessageTests: balloons-and-static-electricity: malformed invocation failed:
string instead of callback
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659438233179/chipper/dist/js/phet-io-wrappers/js/tests/CrossFrameMessageTests.js:89:16
at Array.phetioInitializedListenerFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659438233179/chipper/dist/js/phet-io-wrappers/common/js/Client.js:865:9)
at Client.dispatch (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659438233179/chipper/dist/js/phet-io-wrappers/common/js/Client.js:460:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659438233179/chipper/dist/js/phet-io-wrappers/common/js/Client.js:329:24
at Array.forEach (<anonymous>)
at windowMessageListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1659438233179/chipper/dist/js/phet-io-wrappers/common/js/Client.js:315:27)

id: Bayes Puppeteer
Snapshot from 8/2/2022, 5:03:53 AM
```

**Comment by zepumph** [comment]
I didn't see this locally because phetmarks wasn't automatically enabling assertions in wrapper unit tests like all other wrappers, fixed in the above commit. I'll take a look at the problem, but it is coming from the work I did in https://github.com/phetsims/phet-io-wrappers/issues/445

**Comment by zepumph** [comment]
Looks like SimVersion was polluting the global script source because assert was defined outside the IIFE. Fixed above and passing locally.
