### ISSUE TITLE
CT: error TODO should have an issue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#162]
Appearing in CTQ but not Slack#continuous-testing for a couple of days:

```
code: 1
stdout:
Running "lint-everything" task


aqua:


/data/share/phet/continuous-quick-server/aqua/js/MultiSnapshotComparison.ts
10:1 error TODO should have an issue: TODO: allow linting (it's not finding common definitions) todo-should-have-issue

/data/share/phet/continuous-quick-server/aqua/js/PatientMultiSnapshotComparison.ts
10:1 error TODO should have an issue: TODO: allow linting (it's not finding common definitions) todo-should-have-issue

/data/share/phet/continuous-quick-server/aqua/js/server/QuickServer.js
285:3 error TODO should have an issue: *
* Checks the error messages and reports the current status to the logs and Slack.
*
* @param {boolean} broken
* @param {boolean} lastBroken
* @private
* TODO for @chrisklus: add comments to this function
todo-should-have-issue

✖ 3 problems (3 errors, 0 warnings)


Fatal error: Perennial task failed:
Error: No files matching '../scenery-lab-demo' were found.
at FileEnumerator.iterateFiles (/data/share/phet/continuous-quick-server/chipper/node_modules/eslint/lib/cli-engine/file-enumerator.js:320:27)
at iterateFiles.next (<anonymous>)
at CLIEngine.executeOnFiles (/data/share/phet/continuous-quick-server/chipper/node_modules/eslint/lib/cli-engine/cli-engine.js:786:48)
at ESLint.lintFiles (/data/share/phet/continuous-quick-server/chipper/node_modules/eslint/lib/eslint/eslint.js:551:23)
at lintOneRepo (/data/share/phet/continuous-quick-server/chipper/js/grunt/lint.js:119:32)
at lint (/data/share/phet/continuous-quick-server/chipper/js/grunt/lint.js:169:27)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /data/share/phet/continuous-quick-server/perennial/js/grunt/Gruntfile.js:544:31
at async wrap (/data/share/phet/continuous-quick-server/perennial/js/grunt/Gruntfile.js:44:7)
Full Error details:
Error: No files matching '../scenery-lab-demo' were found.

stderr:
```

**Comment by jonathanolson** [comment]
Resolved it by pulling aqua on CT
