### ISSUE TITLE
Handle 414 errors

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#182]
The firefox is giving errors, I believe because the headers are too long:

```
48|ct-node | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
48|ct-node | Error: Request failed with status code 414
48|ct-node |     at createError (/data/share/phet/continuous-testing/ct-node-client/aqua/node_modules/axios/lib/core/createError.js:16:15)
48|ct-node |     at settle (/data/share/phet/continuous-testing/ct-node-client/aqua/node_modules/axios/lib/core/settle.js:17:12)
48|ct-node |     at IncomingMessage.handleStreamEnd (/data/share/phet/continuous-testing/ct-node-client/aqua/node_modules/axios/lib/adapters/http.js:322:11)
48|ct-node |     at IncomingMessage.emit (node:events:525:35)
48|ct-node |     at endReadableNT (node:internal/streams/readable:1359:12)
48|ct-node |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by zepumph** [comment]
We can increase the size with this, but first we should understand the problem better. It has only happened a few times though for the firefox client, so let's try to reproduce first.

**Comment by zepumph** [comment]
This is likely not causing too much trouble, but I will note https://github.com/phetsims/aqua/issues/178 as the parent issue.

**Comment by zepumph** [comment]
This isn't worth keeping open given how rarely it is occurring, if it pops up more often, we will reopen.

**Comment by zepumph** [comment]
There are a few more of these over on bayes:

```
[phet-admin@bayes logs]$ cat /home/phet-admin/.pm2/logs/ct-node-puppeteer-client-out-*.log  | grep " 414"
2023-05-15T10:57:19: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T12:31:55: Fatal error: Request failed with status code 414
2023-05-15T13:54:17: info: [CONSOLE] listenerOrder random seed: 414288
[CONSOLE] listenerOrder random seed: 414288
2023-05-15T18:16:44: Fatal error: Request failed with status code 414
2023-05-16T03:28:02: Fatal error: Request failed with status code 414
2023-05-16T08:16:41: Fatal error: Request failed with status code 414
2023-05-14T04:34:12: info: [CONSOLE] Getting the state took 414 ms.
2023-05-14T14:52:07: info: [CONSOLE] Getting the state took 414 ms.
2023-05-16T16:11:46: info: [CONSOLE] listenerOrder random seed: 414527
2023-05-15T14:13:11: Fatal error: Request failed with status code 414
2023-05-14T04:34:07: info: [CONSOLE] Setting the state took 414 ms.
2023-05-14T02:07:06: info: [CONSOLE] Getting the state took 414 ms.
2023-05-14T04:03:26: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T01:21:21: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T06:50:52: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T20:43:23: Fatal error: Request failed with status code 414
2023-05-14T14:03:19: info: [CONSOLE] Getting the state took 414 ms.
2023-05-14T19:28:31: info: [CONSOLE] Setting the state took 414 ms.
2023-05-16T12:53:06: info: [CONSOLE] listenerOrder random seed: 414701
2023-05-14T05:40:30: info: [CONSOLE] Setting the state took 414 ms.
2023-05-14T23:20:49: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T05:09:59: info: [CONSOLE] Setting the state took 414 ms.
2023-05-17T17:45:54: Fatal error: Request failed with status code 414
2023-05-14T06:34:26: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T22:32:31: info: [CONSOLE] listenerOrder random seed: 414894
2023-05-16T06:34:04: info: [CONSOLE] listenerOrder random seed: 41419
2023-05-14T06:11:37: info: [CONSOLE] Setting the state took 414 ms.
2023-05-18T08:12:01: Fatal error: Request failed with status code 414
2023-05-14T14:28:02: info: [CONSOLE] Getting the state took 414 ms.
2023-05-15T06:11:44: info: [CONSOLE] Getting the state took 414 ms.
2023-05-16T10:49:30: Fatal error: Request failed with status code 414
2023-05-14T15:39:37: info: [CONSOLE] Getting the state took 414 ms.
2023-05-15T07:28:38: info: [CONSOLE] Getting the state took 414 ms.
2023-05-15T14:53:26: info: [CONSOLE] listenerOrder random seed: 414364
2023-05-17T10:27:55: Fatal error: Request failed with status code 414
2023-05-14T03:48:58: info: [CONSOLE] Getting the state took 414 ms.
2023-05-14T05:54:07: info: [CONSOLE] Setting the state took 414 ms.
2023-05-14T22:03:13: info: [CONSOLE] Getting the state took 414 ms.
[CONSOLE] Getting the state took 414 ms.
2023-05-14T22:09:35: Fatal error: Request failed with status code 414
2023-05-16T04:01:17: Fatal error: Request failed with status code 414
2023-05-16T14:53:44: Fatal error: Request failed with status code 414
2023-05-14T13:10:38: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T14:21:26: Fatal error: Request failed with status code 414
2023-05-16T16:00:31: Fatal error: Request failed with status code 414
2023-05-14T06:02:32: info: [CONSOLE] Getting the state took 414 ms.
2023-05-14T06:53:59: info: [CONSOLE] Setting the state took 414 ms.
2023-05-14T06:54:02: info: [CONSOLE] Setting the state took 414 ms.
2023-05-14T09:31:59: info: [CONSOLE] Setting the state took 414 ms.
2023-05-14T11:45:05: info: [CONSOLE] Setting the state took 414 ms.
2023-05-14T13:54:54: info: [CONSOLE] Getting the state took 414 ms.
2023-05-15T02:02:54: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T12:25:22: Fatal error: Request failed with status code 414
2023-05-18T04:34:14: info: [CONSOLE] listenerOrder random seed: 41493
2023-05-15T02:06:36: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T05:58:35: info: [CONSOLE] Setting the state took 414 ms.
2023-05-15T10:30:00: info: [CONSOLE] listenerOrder random seed: 414643

```
