### ISSUE TITLE
CT snapshots filling up sparky

### ISSUE THREAD

**Issue by zepumph** [phetsims/aqua#224]
@samreid and I found that binder was taking up 13GB and being copied into each new snapshot. This caused us to use all 1TB on /data on sparky. We removed old snapshots and ran `git gc` to clean up the copy of binder/ on sparky checkouts. 

Then during a restart, we lost the history of CT, and it only had one column left. I believe this caused us to "drop" 20 or so checkouts, never to get cleaned up. We should see if that is the case. Here is the list of snapshots before deleting `17323*` just now.

```
drwxr-xr-x. 205 phet phet 8192 Nov 22 15:29 1732314183328
drwxr-xr-x. 205 phet phet 8192 Nov 22 15:44 1732315111070
drwxr-xr-x. 205 phet phet 8192 Nov 22 18:02 1732323547394
drwxr-xr-x. 205 phet phet 8192 Nov 23 03:21 1732357083771
drwxr-xr-x. 205 phet phet 8192 Nov 23 04:10 1732360013497
drwxr-xr-x. 205 phet phet 8192 Nov 23 10:24 1732382432212
drwxr-xr-x. 205 phet phet 8192 Nov 23 10:35 1732382953162
drwxr-xr-x. 205 phet phet 8192 Nov 23 11:11 1732385289212
drwxr-xr-x. 205 phet phet 8192 Nov 23 11:38 1732386845727
drwxr-xr-x. 205 phet phet 8192 Nov 23 16:36 1732404754886
drwxr-xr-x. 205 phet phet 8192 Nov 23 17:35 1732408315886
drwxr-xr-x. 205 phet phet 8192 Nov 23 18:14 1732410657656
drwxr-xr-x. 205 phet phet 8192 Nov 23 19:53 1732416576746
drwxr-xr-x. 205 phet phet 8192 Nov 24 04:41 1732448233967
drwxr-xr-x. 205 phet phet 8192 Nov 25 04:20 1732533382325
drwxr-xr-x. 205 phet phet 8192 Nov 25 10:05 1732554077051
drwxr-xr-x. 205 phet phet 8192 Nov 25 11:13 1732558199708
drwxr-xr-x. 205 phet phet 8192 Nov 25 11:28 1732558938210
drwxr-xr-x. 205 phet phet 8192 Nov 25 12:25 1732562478513
drwxr-xr-x. 205 phet phet 8192 Nov 25 13:45 1732567311905
drwxr-xr-x.   3 phet phet   33 Nov 25 14:37 1732570626905
drwxr-xr-x. 205 phet phet 8192 Nov 25 15:08 1732572225712
drwxr-xr-x. 205 phet phet 8192 Nov 25 15:48 1732574748708
drwxr-xr-x. 205 phet phet 8192 Nov 25 17:19 1732580258150
drwxr-xr-x. 205 phet phet 8192 Nov 25 17:26 1732580609218
drwxr-xr-x. 205 phet phet 8192 Nov 25 17:32 1732580993843
drwxr-xr-x. 205 phet phet 8192 Nov 25 17:43 1732581633638
drwxr-xr-x. 205 phet phet 8192 Nov 25 18:05 1732582996574
drwxr-xr-x. 205 phet phet 8192 Nov 25 18:20 1732583883505
drwxr-xr-x. 205 phet phet 8192 Nov 26 04:22 1732619909043
drwxr-xr-x. 205 phet phet 8192 Nov 26 09:04 1732636817110
drwxr-xr-x. 205 phet phet 8192 Nov 26 10:02 1732640326691
drwxr-xr-x. 205 phet phet 8192 Nov 26 10:40 1732642594906
drwxr-xr-x. 205 phet phet 8192 Nov 26 10:56 1732643428114
drwxr-xr-x. 205 phet phet 8192 Nov 26 11:43 1732646388306

**Comment by zepumph** [comment]
Let's make sure that we have new relic monitoring disk usage as well.

**Comment by zepumph** [comment]
The largest part of the issue seems to be that we can lose a snapshot in the state json and then it lingers forever in the directory. I added code that will delete dirs that aren't in the snapshots list on startup. This automatically deleted a lot of dirs, but I feel like the other part of the problem is why a restart has such a tendency to drop snapshots from the state. And so I also added a hook like we use in QuickServer to save the JSON state before shutting down the process, just in case. 

After restarting ct-main with these changes, it auto deleted all down to 20 snapshots. I believe we will have a much cleaner time here in the future, but I also want to note that I'd like to check in on this, because I'm a bit worried about what may happen over time. I'll review on Monday.

**Comment by zepumph** [comment]
I believe I have fixed this now. There was what I think of as a transient error that has been showing up on CT for the last 5 says which has meant that no snapshots have been getting deleted:

```
 error: snapshot error: RangeError: Invalid string length
0|ct-main  | 2024-12-03T15:47:19: error: autosave error: RangeError: Invalid string length RangeError: Invalid string length
0|ct-main  | 2024-12-03T15:47:19:     at JSON.stringify (<anonymous>)
0|ct-main  | 2024-12-03T15:47:19:     at ContinuousServer.saveToFile (/data/share/phet/continuous-testing/ct-main/aqua/js/server/ContinuousServer.js:346:43)
0|ct-main  | 2024-12-03T15:47:19:     at ContinuousServer.autosaveLoop (/data/share/phet/continuous-testing/ct-main/aqua/js/server/ContinuousServer.js:759:14)
0|ct-main  | 2024-12-03T16:12:45:

```

I hope a restart will have fixed this. I'll check back tomorrow.

**Comment by zepumph** [comment]
CT just got to 20 snapshots at 10:22 this morning. If we see that this snapshot is deleted, this issue can be closed:

```
drwxr-xr-x. 205 phet phet 8192 Dec  3 15:52 1733266207418
```

**Comment by zepumph** [comment]
We are deleting old snapshots! Closing
