### ISSUE TITLE
Use same testing framework for Node and HTML?

### ISSUE THREAD

**Issue by samreid** [phetsims/aqua#34]
We started using mocha for chipper tests, and we should consider using it for browser tests too.  I noticed in http://www.techtalkdc.com/which-javascript-test-library-should-you-use-qunit-vs-jasmine-vs-mocha/ that Mocha can use any assertion library--I wonder if that means we can use our ASSERT/assert.js for it and what that would imply.  @jonathanolson thoughts?

**Comment by samreid** [comment]
Here's what an example browser report looks like:

![image](https://user-images.githubusercontent.com/679486/34440322-a7bcb21a-ec71-11e7-8444-9fecffa5ff6b.png)

Not too impressive.  I also realized QUnit also supports Node, so maybe we should use that?  In any case, we should decide this as a team.  Flagging for developer meeting.

**Comment by ariel-phet** [comment]
@jonathanolson will take a quick look at how Qunit works for node.js and report back for dev meeting. We can discuss more then.

**Comment by samreid** [comment]
Sample usage is on QUnit's front page: https://qunitjs.com/

**Comment by jonathanolson** [comment]
I'll do a quick rewrite to use qunit testing. For sake of a comparison (and what in mocha was useful that I'd like to have or mimic using qunit), I'll show an example test and the full test output for both.

**Comment by jonathanolson** [comment]
Mocha, all tests passing:
```
olson@MSI MINGW64 ~/phet/git/chipper (2.0)
$ mocha


  Chains building
    √ Build (no args) (43682ms)
    √ Build (with added HTMLs) (45256ms)
    √ Build (no uglification) (15347ms)
    √ Build (no mangling) (30233ms)
    √ Build (instrument) (14917ms)
    √ Build (all locales) (36131ms)
    √ Build (es,zh_CN locales) (32902ms)
    √ Build (phet brand only) (18834ms)
    √ Build (phet-io brand only) (19917ms)
    √ Build (one-off) (32827ms)

  Generation
    √ Development HTML (1741ms)
    √ Test HTML (1727ms)
    √ Colors HTML (1685ms)
    √ A11Y View HTML (1686ms)
    √ Config (1698ms)
    √ Test Config (1721ms)
    √ Published README (1794ms)
    √ Unpublished README (1743ms)
    √ Copyright (2166ms)


  19 passing (5m)
```

**Comment by jonathanolson** [comment]
Mocha when I cause a test failure:
```
  11) Generation
       Development HTML:
     grunt.cmd generate-development-html in ../chains failed with exit code 1 and stdout:
Running "generate-development-html" task
Fatal error: Perennial task failed:
Error: Yay testing the testing frameworks
  at module.exports (C:\Users\olson\phet\git\chipper\js\grunt\generateDevelopmentHTML.js:39:11)
  at grunt.registerTask.wrapTask (C:\Users\olson\phet\git\chipper\js\grunt\Gruntfile.js:200:7)
  at Object.<anonymous> (C:\Users\olson\phet\git\chipper\js\grunt\Gruntfile.js:85:13)
  at Object.thisTask.fn (C:\Users\olson\phet\git\chains\node_modules\grunt\lib\grunt\task.js:73:16)
  at Object.<anonymous> (C:\Users\olson\phet\git\chains\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (C:\Users\olson\phet\git\chains\node_modules\grunt\lib\util\task.js:244:24)
  at Task.<anonymous> (C:\Users\olson\phet\git\chains\node_modules\grunt\lib\util\task.js:293:12)
  at Task.start (C:\Users\olson\phet\git\chains\node_modules\grunt\lib\util\task.js:302:5)
  at Object.grunt.tasks (C:\Users\olson\phet\git\chains\node_modules\grunt\lib\grunt.js:155:8)
  at Object.module.exports [as cli] (C:\Users\olson\phet\git\chains\node_modules\grunt\lib\grunt\cli.js:27:9)
  at Object.<anonymous> (C:\Users\olson\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt:44:20)
  at Module._compile (module.js:641:30)
  at Object.Module._extensions..js (module.js:652:10)
  at Module.load (module.js:560:32)
  at tryModuleLoad (module.js:503:12)
  at Function.Module._load (module.js:495:3)
  at Function.Module.runMain (module.js:682:10)
  at startup (bootstrap_node.js:191:16)
  at bootstrap_node.js:613:3
```

**Comment by jonathanolson** [comment]
QUnit output:
```
$ qunit
TAP version 13
ok 1 Chains building > Build (no args)
ok 2 Chains building > Build (with added HTMLs)
ok 3 Chains building > Build (no uglification)
ok 4 Chains building > Build (no mangling)
ok 5 Chains building > Build (instrument)
ok 6 Chains building > Build (all locales)
ok 7 Chains building > Build (es,zh_CN locales)
ok 8 Chains building > Build (phet brand only)
ok 9 Chains building > Build (phet-io brand only)
ok 10 Chains building > Build (one-off)
ok 11 Generation > Development HTML
ok 12 Generation > Test HTML
ok 13 Generation > Colors HTML
ok 14 Generation > A11Y View HTML
ok 15 Generation > Config
ok 16 Generation > Test Config
ok 17 Generation > Published README
ok 18 Generation > Unpublished README
ok 19 Generation > Copyright
1..19
# pass 19
# skip 0
# todo 0
# fail 0
```

Error output is similar.

QUnit is good enough (and supports async functions, or anything that returns a Promise), so I'm just going to move forward with the swap to it.

**Comment by jonathanolson** [comment]
Moved everything off mocha to qunit. @samreid, anything else to do here?

**Comment by samreid** [comment]
I see 3 occurrences of "Unit tests, run with `mocha`" that should probably be updated.  The rest of the changes seem good.  I installed qunit and ran the perennial tests and it seemed reasonable.

**Comment by jonathanolson** [comment]
Changed references, closing. Thanks!
