### ISSUE TITLE
add query parameter to CT output

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/aqua#65]
When an error is detected, CT labels its output like this:

```
projectile-motion : xss-fuzz : run
Error: Assertion failed: Corner overlap on left edge
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1547658484416/assert/js/assert.js:22:13)
...
```

In order to reproduce this, I have to take the test name ("xss-fuzz") and search for it in continuous-server.js to find what query parameters were used.    Would it be possible to print the query parameters in the CT output?  E.g. the above could look like:

```
projectile-motion : xss-fuzz : run : ?brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Error: Assertion failed: Corner overlap on left edge
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1547658484416/assert/js/assert.js:22:13)
...
```

**Comment by jonathanolson** [comment]
Added output of query parameters for sim runs, waiting to make sure it works nicely.

**Comment by jonathanolson** [comment]
Query parameters are now shown, e.g.:
```
models-of-the-hydrogen-atom : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Corner overlap on left edge
Error: Assertion failed: Corner overlap on left edge
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/assert/js/assert.js:22:13)
    at Function.Shape.roundedRectangleWithRadii (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/kite/js/Shape.js?bust=1547747232039:1952:15)
    at createButtonShape (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/sun/js/buttons/RectangularButtonView.js?bust=1547747232039:38:18)
    at ComboBoxButton.RectangularButtonView [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/sun/js/buttons/RectangularButtonView.js?bust=1547747232039:115:28)
    at new RectangularPushButton (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/sun/js/buttons/RectangularPushButton.js?bust=1547747232039:47:27)
    at new ComboBoxButton (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/sun/js/ComboBoxButton.js?bust=1547747232039:110:7)
    at new ComboBox (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/sun/js/ComboBox.js?bust=1547747232039:256:19)
    at new TimeControls (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/models-of-the-hydrogen-atom/js/spectra/view/TimeControls.js?bust=1547747232039:61:25)
    at new SpectraScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/models-of-the-hydrogen-atom/js/spectra/view/SpectraScreenView.js?bust=1547747232039:107:24)
    at SpectraScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1547745503498/models-of-the-hydrogen-atom/js/spectra/SpectraScreen.js?bust=1547747232039:35:34)
id: Bayes Chrome
Approximately 1/17/2019, 10:18:23 AM
```

Does that look good?

**Comment by pixelzoom** [comment]
Looks great. I wasn't sure if this was deployed, so back to @jonathanolson.

**Comment by pixelzoom** [comment]
@jonathanolson hasn't replied, and it looks like this is the case in CT. So I'm just going to close this issue.
